// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi0QbdNpGvt0J86qEhc5Y-7btTXCv0OYI',
    appId: '1:441058970553:web:1c4712bf1a8ec54b6d8468',
    messagingSenderId: '441058970553',
    projectId: 'chat-app-78095',
    authDomain: 'chat-app-78095.firebaseapp.com',
    storageBucket: 'chat-app-78095.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLVguTY4Qf8C_ON6mh7-kx8eCsQaGpYJw',
    appId: '1:441058970553:android:90516099eb6c4c786d8468',
    messagingSenderId: '441058970553',
    projectId: 'chat-app-78095',
    storageBucket: 'chat-app-78095.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhTgPrcKsFWx7LCL7SJuHdDFSgtq1NdI8',
    appId: '1:441058970553:ios:84ca95f462e4c4836d8468',
    messagingSenderId: '441058970553',
    projectId: 'chat-app-78095',
    storageBucket: 'chat-app-78095.appspot.com',
    androidClientId: '441058970553-lso2vsii40mnqqf334e7rntstusnpseh.apps.googleusercontent.com',
    iosClientId: '441058970553-acjijfa9flr6r9ct72s9d68i2moik7g9.apps.googleusercontent.com',
    iosBundleId: 'com.example.testapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhTgPrcKsFWx7LCL7SJuHdDFSgtq1NdI8',
    appId: '1:441058970553:ios:84ca95f462e4c4836d8468',
    messagingSenderId: '441058970553',
    projectId: 'chat-app-78095',
    storageBucket: 'chat-app-78095.appspot.com',
    iosBundleId: 'com.example.testapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDi0QbdNpGvt0J86qEhc5Y-7btTXCv0OYI',
    appId: '1:441058970553:web:f17999c04da5163b6d8468',
    messagingSenderId: '441058970553',
    projectId: 'chat-app-78095',
    authDomain: 'chat-app-78095.firebaseapp.com',
    storageBucket: 'chat-app-78095.appspot.com',
  );
}